Profile page without api
TopNameOrganization/top-name-game-repo pull request #3
Opened 2023-02-03 17:17 UTC by alexweb79

### Какую задачу решаем
Добавление страницы профиля, пока без api

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-04 07:52 UTC, octomine commented
ревьювера от яндекса реквестим только после того, как аппрувнули внутри команды ))

2023-02-04 08:15 UTC, Prchnk commented
мне кажется что ревьюера яндекса нужно где-то за неделю до демо дергать, мало пока написано

2023-02-04 13:47 UTC, octomine commented on packages/client/src/pages/profile/Profile.tsx
> +        <ThemeProvider theme={theme}>
ThemeProvider должен быть в App.tsx, чтоб тема во всё приложение прокидывалась, в страницах он не нужен (ну только если не нужно темизировать отдельную страницу)

2023-02-04 18:18 UTC, alexweb79 commented on packages/client/src/pages/profile/Profile.tsx
> +        <ThemeProvider theme={theme}>
Понял, убрал

2023-02-04 18:34 UTC, octomine approved these changes

2023-02-06 15:33 UTC, MaximOvsyannikov commented on packages/client/src/components/profile/ProfileForm.tsx
> +    const validationSchema = yup.object({
стоит вынести за пределы компонента, чтоб не создавала константу каждый ререндер

2023-02-06 15:34 UTC, MaximOvsyannikov commented on packages/client/src/components/profile/ProfileForm.tsx
> +    const [profile, setProfile] = React.useState<IProfile>({
формик хранит значения филдов в себе, незачем дублировать форму в стейте

2023-02-06 15:35 UTC, MaximOvsyannikov commented on packages/client/src/components/profile/ProfileForm.tsx
> +            <TextField
думаю попозже создать компоненты филдов отдельно, чтоб вынести ы них общие пропсы (а то дублируем сейчас) и обработчики, блюр например и всякое такое. а пока думаю можно подублировать)))

2023-02-06 16:27 UTC, alexweb79 commented on packages/client/src/components/profile/ProfileForm.tsx
> +    const validationSchema = yup.object({
Вынес

2023-02-06 16:28 UTC, alexweb79 commented on packages/client/src/components/profile/ProfileForm.tsx
> +    const [profile, setProfile] = React.useState<IProfile>({
пофиксил

2023-02-06 18:12 UTC, Prchnk commented on .env
> +POSTGRES_USER=postgres
а в этом ПР только верстка? зачем тут это?

2023-02-06 18:15 UTC, Prchnk reviewed
вопрос по файлам .yarn/releases/yarn-1.22.19.cjs и .yarn/install-state.gz а что это и нужно ли это?
 в package.json используется yarn, при этом сгенерен lock-файл нпм

2023-02-06 18:18 UTC, Prchnk commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-1.22.19.cjs
а это зачем?)

2023-02-06 19:19 UTC, alexweb79 commented on .env
> +POSTGRES_USER=postgres
примерчик задублировался, убрал

2023-02-06 19:24 UTC, alexweb79 commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-1.22.19.cjs
убрал

2023-02-06 19:25 UTC, alexweb79 commented
> вопрос по файлам .yarn/releases/yarn-1.22.19.cjs и .yarn/install-state.gz а что это и нужно ли это? в package.json используется yarn, при этом сгенерен lock-файл нпм. yarn или npm используем?

у меня не было yarn, сейчас разберусь :) Используем yarn

2023-02-06 20:30 UTC, Prchnk approved these changes

2023-02-07 09:21 UTC, MaximOvsyannikov approved these changes

2023-02-07 14:07 UTC, Brarion requested changes
Супер работа, только у вас есть папка `components` и папка `pages`. Внутри `pages` лежит станица `profile`, а внутри `components` лежит папка `profile`, в которой компоненты, которые относятся только к профилю. Лучше в `/pages/profile` создать папку `components` и в неё перенести эти компоненты. Так будет ясно, что конкретно эти компоненты применяются только к этой странице, а сейчас у вас не совсем очевидно это

2023-02-07 14:07 UTC, Brarion commented on packages/client/src/components/profile/ProfileForm.tsx
> +            }
Тут можно в виде тернарника написать вот так (только красиво ещё отступы там сделать надо, ну, как умеете):
```tsx
{
  !isDisabled ? (<Button
    onClick={handleChangeIsDisabled}
    type="button"
    fullWidth
    variant="contained"
    sx={{ mt: 5, mb: 2 }}
  >
    Edit Profile
  </Button>)
    : (
      <Button
        type="submit"
        fullWidth
        variant="contained"
        sx={{ mt: 5, mb: 2 }}
      >
        Save Profile
      </Button>)
}
```

2023-02-07 14:16 UTC, Brarion requested changes
Не подумал сразу по поводу схемы валидации и компонентов. Для каждого компонента лучше создать папку отдельную. В ней будут ещё дополнительные файлы для каждого компонента: стили, валидации, константы и др.

2023-02-07 14:16 UTC, Brarion commented on packages/client/src/components/profile/ProfileForm.tsx
> +});
Лучше вынести в отдельный файл типа `validation.ts`

2023-02-07 18:44 UTC, alexweb79 commented on packages/client/src/components/profile/ProfileForm.tsx
> +});
Согласен, вынес

2023-02-07 18:45 UTC, alexweb79 commented on packages/client/src/components/profile/ProfileForm.tsx
> +            }
Можно и так, сделал

2023-02-07 18:49 UTC, alexweb79 commented
> Супер работа, только у вас есть папка `components` и папка `pages`. Внутри `pages` лежит станица `profile`, а внутри `components` лежит папка `profile`, в которой компоненты, которые относятся только к профилю. Лучше в `/pages/profile` создать папку `components` и в неё перенести эти компоненты. Так будет ясно, что конкретно эти компоненты применяются только к этой странице, а сейчас у вас не совсем очевидно это

Над структурой с командой еще пока думаем, как будет удобнее сделать.
Спасибо за направление, будем иметь ввиду, если это не критично, то пока пропущу.

Еще раз спасибо!

2023-02-08 11:00 UTC, Brarion commented
> > Супер работа, только у вас есть папка `components` и папка `pages`. Внутри `pages` лежит станица `profile`, а внутри `components` лежит папка `profile`, в которой компоненты, которые относятся только к профилю. Лучше в `/pages/profile` создать папку `components` и в неё перенести эти компоненты. Так будет ясно, что конкретно эти компоненты применяются только к этой странице, а сейчас у вас не совсем очевидно это
> 
> Над структурой с командой еще пока думаем, как будет удобнее сделать. Спасибо за направление, будем иметь ввиду, если это не критично, то пока пропущу.
> 
> Еще раз спасибо!

Да, это не критично, коллега из команды вашей сказал, что вы договариваетесь пока что, как работать с папками, поэтому всё хорошо)

2023-02-08 11:01 UTC, Brarion approved these changes
Отличный `PR`)

2023-02-08 18:03 UTC, merged