Feat 222 4 leader board
TopNameOrganization/top-name-game-repo pull request #4
Opened 2023-02-04 14:15 UTC by octomine

добавлена страница рекордов (leaderboard) без апи

ну и ещё добавлен ThemeProvider в App.tsx и от туда же удалён fetch, потому что он ничего не фетчит и ошибку в консоль кидает

2023-02-06 14:55 UTC, alexweb79 approved these changes

2023-02-06 15:41 UTC, MaximOvsyannikov approved these changes

2023-02-06 20:32 UTC, Prchnk approved these changes

2023-02-07 14:12 UTC, Brarion requested changes
Красота)

2023-02-07 14:12 UTC, Brarion commented on packages/client/src/pages/LeaderBoardPage.tsx
> +            <TableRow key={index}>
Не советую использовать `index` для `key`, лучше выбрать что-то другое, если есть такая возможность

2023-02-07 14:12 UTC, Brarion commented on packages/client/src/pages/LeaderBoardPage.tsx
> +  ]
Лучше вынести хоть и временную, но всё же константу над компонентом вот так:
```tsx
  const data = [
    { name: 'aaa', level: 10, score: 1000 },
    { name: 'bbb', level: 8, score: 500 },
    { name: 'ccc', level: 2, score: 20 },
  ]
  
  const LeaderBoardPage = () => {
    ...
  }
```
или в отдельный файл `constants.ts` рядом с этим компонентом

2023-02-07 14:12 UTC, Brarion commented on packages/client/src/pages/LeaderBoardPage.tsx
> +import React from 'react'
В целом по этому файлу: в других `PR` я видел, что компоненты-страницы выделены в отдельные папки. Лучше так и делать, то есть создайте в папке `pages` папку `LeaderBoardPage`, а внутрь уже положите этот файл

2023-02-07 14:45 UTC, octomine commented on packages/client/src/pages/LeaderBoardPage.tsx
> +import React from 'react'
ну это такой типа атомик, mui - атомы и молекулы, components - организмы, pages - страницы, просто пока ещё в рамках команды не выработали общего понимания что и как именно, но вчера на синке договорились, что того, как всё смержим - заведём задачу на рефакторинг и приведём всё к единому виду

2023-02-07 14:45 UTC, octomine commented on packages/client/src/pages/LeaderBoardPage.tsx
> +  ]
да, виноват, такая константа внутри компонента - нехорошо, перенёс выше

2023-02-07 14:45 UTC, octomine commented on packages/client/src/pages/LeaderBoardPage.tsx
> +            <TableRow key={index}>
да, но тут как-то ничего более другого unique под рукой не оказалось, на всякий случай сделал `key${index}`

2023-02-07 14:47 UTC, octomine commented
> Красота)

спасибо )

2023-02-08 10:56 UTC, Brarion approved these changes
Нравится такие `PR` смотреть)

2023-02-08 10:56 UTC, Brarion commented on packages/client/src/pages/LeaderBoardPage.tsx
> +import React from 'react'
Хорошо, молодцы, что договариваетесь, как будете работать в команде)

2023-02-09 07:04 UTC, merged