signin page without api
TopNameOrganization/top-name-game-repo pull request #5
Opened 2023-02-05 19:25 UTC by MaximOvsyannikov

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-06 14:59 UTC, alexweb79 approved these changes

2023-02-06 14:59 UTC, alexweb79 commented on packages/client/src/components/signIn/SignInForm.tsx
> +interface SignInFordData {
Тут опечатка, наверное имелось ввиду SignInFormData

2023-02-06 14:59 UTC, alexweb79 commented on packages/client/src/components/signIn/SignInForm.tsx
> +    onSubmit: (data: SignInFordData) => {
Тут опечатка, наверное имелось ввиду SignInFormData

2023-02-06 15:02 UTC, octomine approved these changes

2023-02-07 09:45 UTC, Prchnk approved these changes

2023-02-07 14:14 UTC, Brarion commented
Описание поправьте, пожалуйста)

2023-02-07 14:14 UTC, Brarion requested changes
Красота)

2023-02-07 14:14 UTC, Brarion commented on packages/client/src/components/signIn/SignInForm.tsx
> +})
Лучше вынести в отдельный файл типа `validation.ts`

2023-02-08 12:08 UTC, Brarion approved these changes
💯

2023-02-08 15:29 UTC, merged