signup page without api
TopNameOrganization/top-name-game-repo pull request #6
Opened 2023-02-06 16:27 UTC by MaximOvsyannikov

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-07 10:29 UTC, octomine approved these changes

2023-02-07 10:53 UTC, alexweb79 approved these changes

2023-02-07 17:07 UTC, Prchnk approved these changes

2023-02-08 12:10 UTC, Brarion requested changes
Очень хорошо)

2023-02-08 12:10 UTC, Brarion commented on packages/client/src/components/signUp/SignUpForm.tsx
> +  second_name: string
Лучше поменять на `camelCase`, на `JS/TS` обычно его используют

2023-02-08 12:41 UTC, MaximOvsyannikov commented on packages/client/src/components/signUp/SignUpForm.tsx
> +  second_name: string
согласен, только как я понял на данном этапе будем использовать апи регистрации и авторизации из проекта с месенджером, а там именно такой интерфейс, стоит писать в кемел кейсе и мапить дто?

2023-02-09 10:03 UTC, Brarion commented on packages/client/src/components/signUp/SignUpForm.tsx
> +  second_name: string
А, если апи такое, то не обязательно мапить. Тут больше зависит от самого проекта, какой стиль кода принят. Короче, по-разному делают: где-то мапят, где-то нет
Тут лучше оставить, как есть, потому что время тратить не хочется)

2023-02-09 10:14 UTC, MaximOvsyannikov commented on packages/client/src/components/signUp/SignUpForm.tsx
> +  second_name: string
апрув?))))

2023-02-09 10:32 UTC, Brarion approved these changes
Апрув))

2023-02-09 10:38 UTC, merged