Feat/222 18 profile page api
TopNameOrganization/top-name-game-repo pull request #8
Opened 2023-02-08 20:38 UTC by alexweb79

### Какую задачу решаем
Добавил api для страницв профайла

2023-02-09 07:53 UTC, octomine commented on packages/client/src/api/UsersAPI.ts
> +class UsersAPI extends React.Component {
не не не, здесь не надо наследовать от React.Component, здесь вообще наследовать не надо ))

2023-02-09 07:56 UTC, octomine requested changes

2023-02-09 07:56 UTC, octomine commented on packages/client/src/api/UsersAPI.ts
> +  static handleChangeUserProfile = async (data: UserProfileData) => {
ну в общем не принципиально, но мне кажется handle не надо, никакой смысловой нагрузки не несёт, а времени на напечатать чуть отжирает

2023-02-09 07:56 UTC, octomine commented on packages/client/src/api/UsersAPI.ts
> +class UsersAPI extends React.Component {
не не не, здесь не надо наследовать от React.Component, здесь вообще наследовать не надо ))

2023-02-09 08:15 UTC, alexweb79 commented on packages/client/src/api/UsersAPI.ts
> +class UsersAPI extends React.Component {
спасибо, убрал

2023-02-09 08:15 UTC, alexweb79 commented on packages/client/src/api/UsersAPI.ts
> +  static handleChangeUserProfile = async (data: UserProfileData) => {
переименовал :)

2023-02-09 09:22 UTC, octomine approved these changes

2023-02-09 10:39 UTC, Prchnk approved these changes

2023-02-09 22:11 UTC, MaximOvsyannikov approved these changes

2023-02-10 10:49 UTC, Brarion approved these changes
Очень хорошо :fire:

2023-02-11 10:46 UTC, closed without merging